# See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.4
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - rails-backend-bundle-v2-{{ checksum "stylecheck.gemspec" }}
            - rails-backend-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - save_cache:
          key: rails-backend-bundle-v2-{{ checksum "stylecheck.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run RuboCop
          command: bundle exec rake style
